### ISSUE TITLE
Objects saved to root Tree of Woe breaks Tree of Woe

### ISSUE THREAD

**Issue by saraht45** [ChatTheatre/SkotOS#71]
Tree of Woe fails to load when objects are saved to the root directory. Special characters can also be a problem. We should figure out some solution to either disallow special characters/saves to root or update Tree of Woe to handle it better.

**Comment by noahgibbs** [comment]
Cool. I've hotfixed this for testing-8. I'll get the patch into a PR on ChatTheatre/SkotOS soon.

Turns out it's just a Javascript bug. We could probably fix it better (add an "orphaned" or "top-level" folder?), but for now I'm just having the Tree of WOE not display top-level folderless objects since that would break it.

**Comment by noahgibbs** [comment]
This should be fixed now.
